-- E-Commerce Platform - MariaDB Initial Schema
-- Generated from complete code analysis and frontend requirements
-- MariaDB 10.3+ with utf8mb4 charset and InnoDB engine

-- Users table - Core user accounts
CREATE TABLE IF NOT EXISTS `users` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `username` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
    `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    `pass_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `first_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
    `last_name` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
    `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `role` enum('customer','vendor','admin') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'customer',
    `status` enum('active','inactive','pending','suspended') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
    `verified_at` timestamp NULL DEFAULT NULL,
    `avatar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `bio` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `preferences` json DEFAULT NULL,
    `two_fa_enabled` tinyint(1) NOT NULL DEFAULT 0,
    `two_fa_secret` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `last_login_at` timestamp NULL DEFAULT NULL,
    `last_login_ip` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_username` (`username`),
    UNIQUE KEY `idx_email` (`email`),
    KEY `idx_role` (`role`),
    KEY `idx_status` (`status`),
    KEY `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Categories table - Hierarchical product categories
CREATE TABLE IF NOT EXISTS `categories` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `parent_id` int(11) DEFAULT NULL,
    `slug` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `image_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `sort_order` int(11) NOT NULL DEFAULT 0,
    `status` enum('active','inactive') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
    `meta_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `meta_description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_slug` (`slug`),
    KEY `idx_parent_id` (`parent_id`),
    KEY `idx_status` (`status`),
    KEY `idx_sort_order` (`sort_order`),
    CONSTRAINT `fk_categories_parent` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Vendors table - Seller information
CREATE TABLE IF NOT EXISTS `vendors` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `user_id` int(11) NOT NULL,
    `business_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    `business_type` enum('individual','business','corporation') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'individual',
    `tax_id` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `business_address` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `business_phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `business_email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `website` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `logo_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `banner_url` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `status` enum('pending','approved','suspended','rejected') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
    `commission_rate` decimal(5,2) NOT NULL DEFAULT 10.00,
    `payment_details` json DEFAULT NULL,
    `business_documents` json DEFAULT NULL,
    `approved_at` timestamp NULL DEFAULT NULL,
    `approved_by` int(11) DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_user_id` (`user_id`),
    KEY `idx_status` (`status`),
    KEY `idx_business_name` (`business_name`),
    CONSTRAINT `fk_vendors_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_vendors_approver` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Products table - Core product information
CREATE TABLE IF NOT EXISTS `products` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `vendor_id` int(11) NOT NULL,
    `category_id` int(11) NOT NULL,
    `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `slug` varchar(275) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `short_description` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `sku` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `barcode` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `price` decimal(10,2) NOT NULL,
    `sale_price` decimal(10,2) DEFAULT NULL,
    `cost_price` decimal(10,2) DEFAULT NULL,
    `stock_quantity` int(11) NOT NULL DEFAULT 0,
    `min_stock_level` int(11) NOT NULL DEFAULT 5,
    `max_stock_level` int(11) DEFAULT NULL,
    `weight` decimal(8,2) DEFAULT NULL,
    `dimensions` json DEFAULT NULL,
    `status` enum('active','inactive','draft','archived') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
    `featured` tinyint(1) NOT NULL DEFAULT 0,
    `digital` tinyint(1) NOT NULL DEFAULT 0,
    `downloadable` tinyint(1) NOT NULL DEFAULT 0,
    `virtual` tinyint(1) NOT NULL DEFAULT 0,
    `tags` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `attributes` json DEFAULT NULL,
    `variations` json DEFAULT NULL,
    `shipping_class` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `tax_status` enum('taxable','shipping','none') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'taxable',
    `tax_class` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `meta_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `meta_description` text COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `view_count` int(11) NOT NULL DEFAULT 0,
    `purchase_count` int(11) NOT NULL DEFAULT 0,
    `average_rating` decimal(3,2) NOT NULL DEFAULT 0.00,
    `review_count` int(11) NOT NULL DEFAULT 0,
    `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    PRIMARY KEY (`id`),
    UNIQUE KEY `idx_sku` (`sku`),
    KEY `idx_vendor_id` (`vendor_id`),
    KEY `idx_category_id` (`category_id`),
    KEY `idx_status` (`status`),
    KEY `idx_featured` (`featured`),
    KEY `idx_price` (`price`),
    KEY `idx_name` (`name`),
    KEY `idx_slug` (`slug`),
    KEY `idx_stock_quantity` (`stock_quantity`),
    KEY `idx_created_at` (`created_at`),
    FULLTEXT KEY `idx_search` (`name`,`description`,`tags`),
    CONSTRAINT `fk_products_vendor` FOREIGN KEY (`vendor_id`) REFERENCES `vendors` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_products_category` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Product Images table
CREATE TABLE IF NOT EXISTS `product_images` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `product_id` int(11) NOT NULL,
    `image_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `alt_text` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `is_primary` tinyint(1) NOT NULL DEFAULT 0,
    `sort_order` int(11) NOT NULL DEFAULT 0,
    `file_size` int(11) DEFAULT NULL,
    `width` int(11) DEFAULT NULL,
    `height` int(11) DEFAULT NULL,
    `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
    PRIMARY KEY (`id`),
    KEY `idx_product_id` (`product_id`),
    KEY `idx_is_primary` (`is_primary`),
    KEY `idx_sort_order` (`sort_order`),
    CONSTRAINT `fk_product_images_product` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User Addresses table
CREATE TABLE IF NOT EXISTS `addresses` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `user_id` int(11) NOT NULL,
    `type` enum('billing','shipping','both') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'both',
    `first_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `last_name` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `company` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `address_line1` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
    `address_line2` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `city` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    `state` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
    `postal_code` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
    `country` varchar(2) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'US',
    `phone` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    `is_default` tinyint(1) NOT NULL DEFAULT 0,
    `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
    `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
    PRIMARY KEY (`id`),
    KEY `idx_user_id` (`user_id`),
    KEY `idx_type` (`type`),
    KEY `idx_is_default` (`is_default`),
    CONSTRAINT `fk_addresses_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;